:: Migrations
php artisan make:migration create_accounts_table
php artisan make:migration create_patients_table
php artisan make:migration create_doctors_table
php artisan make:migration create_suppliers_table
php artisan make:migration create_pharmacy_items_table
php artisan make:migration create_logistic_items_table
php artisan make:migration create_general_items_table
php artisan make:migration create_cashier_transactions_table
php artisan make:migration create_cashier_receivables_table
php artisan make:migration create_pharmacy_purchases_table
php artisan make:migration create_pharmacy_withdrawals_table
php artisan make:migration create_pharmacy_cogs_table
php artisan make:migration create_logistic_purchases_table
php artisan make:migration create_logistic_usage_table
php artisan make:migration create_general_purchases_table
php artisan make:migration create_cash_bank_transactions_table
php artisan make:migration create_medical_service_transactions_table
php artisan make:migration create_accounts_payable_table
php artisan make:migration create_accounts_receivable_table
php artisan make:migration create_general_journal_table
php artisan make:migration create_journal_entries_table
php artisan make:migration create_general_ledger_table
php artisan make:migration create_income_statement_table
php artisan make:migration create_balance_sheet_table
php artisan make:migration create_fixed_assets_table

:: Models
php artisan make:model Patient
php artisan make:model Doctor
php artisan make:model Supplier
php artisan make:model Item
php artisan make:model CashierTransaction
php artisan make:model CashierReceivable
php artisan make:model SupplierPurchase
php artisan make:model ConsumableWithdrawal
php artisan make:model CogsCalculation
php artisan make:model LogisticSupplierPurchase
php artisan make:model LogisticUsage
php artisan make:model GeneralSupplierPurchase
php artisan make:model CashBankTransaction
php artisan make:model MedicalServiceTransaction
php artisan make:model AccountsPayable
php artisan make:model AccountsReceivable
php artisan make:model GeneralJournal
php artisan make:model JournalEntry
php artisan make:model GeneralLedger
php artisan make:model IncomeStatement
php artisan make:model BalanceSheet
php artisan make:model FixedAsset

:: Controllers
php artisan make:controller PatientController
php artisan make:controller DoctorController
php artisan make:controller SupplierController
php artisan make:controller ItemController
php artisan make:controller CashierTransactionController
php artisan make:controller CashierReceivableController
php artisan make:controller SupplierPurchaseController
php artisan make:controller ConsumableWithdrawalController
php artisan make:controller CogsCalculationController
php artisan make:controller LogisticSupplierPurchaseController
php artisan make:controller LogisticUsageController
php artisan make:controller GeneralSupplierPurchaseController
php artisan make:controller CashBankTransactionController
php artisan make:controller MedicalServiceTransactionController
php artisan make:controller AccountsPayableController
php artisan make:controller AccountsReceivableController
php artisan make:controller GeneralJournalController
php artisan make:controller JournalEntryController
php artisan make:controller GeneralLedgerController
php artisan make:controller IncomeStatementController
php artisan make:controller BalanceSheetController
php artisan make:controller FixedAssetController